os:
    - linux

sudo: false

language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

env:
    matrix:
        - TRAVIS_NODE_VERSION="0.8"
        - TRAVIS_NODE_VERSION="0.10"
        - TRAVIS_NODE_VERSION="0.12"
        - TRAVIS_NODE_VERSION="iojs-3"
        - TRAVIS_NODE_VERSION="4"
        - TRAVIS_NODE_VERSION="6"
        - TRAVIS_NODE_VERSION="8"
        - TRAVIS_NODE_VERSION="10"
        - TRAVIS_NODE_VERSION="12"
        - TRAVIS_NODE_VERSION="13"
        - TRAVIS_NODE_VERSION="14"
        - TRAVIS_NODE_VERSION="16"

install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then npm config set strict-ssl false ; npm install -g npm@2 ; fi
    - which node
    - node --version
    - which npm
    - npm --version
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
    - $CXX --version

script:
    - npm install
    - node test.js
